<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="8" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-15T04:10:08 IST" name="Default suite" finished-at="2021-01-15T04:10:08 IST" duration-ms="86">
    <groups>
    </groups>
    <test started-at="2021-01-15T04:10:08 IST" name="Default test" finished-at="2021-01-15T04:10:08 IST" duration-ms="86">
      <class name="TestCalculate">
        <test-method is-config="true" signature="init()[pri:0, instance:TestCalculate@a1cdc6d]" started-at="2021-01-15T04:10:08 IST" name="init" finished-at="2021-01-15T04:10:08 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="AllowingMultipleDelimiters()[pri:0, instance:TestCalculate@a1cdc6d]" started-at="2021-01-15T04:10:08 IST" name="AllowingMultipleDelimiters" finished-at="2021-01-15T04:10:08 IST" duration-ms="7" status="FAIL">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: "1*2%3"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: "1*2%3"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
at java.base/java.lang.Integer.parseInt(Integer.java:652)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at Calculator.CheckforNegatives(Calculator.java:58)
at Calculator.CalculateSum(Calculator.java:39)
at Calculator.calculate(Calculator.java:25)
at TestCalculate.AllowingMultipleDelimiters(TestCalculate.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AllowingMultipleDelimiters -->
        <test-method signature="DelimitersofVariableLength()[pri:0, instance:TestCalculate@a1cdc6d]" started-at="2021-01-15T04:10:08 IST" name="DelimitersofVariableLength" finished-at="2021-01-15T04:10:08 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DelimitersofVariableLength -->
        <test-method signature="EmptyStringReturnZero()[pri:0, instance:TestCalculate@a1cdc6d]" started-at="2021-01-15T04:10:08 IST" name="EmptyStringReturnZero" finished-at="2021-01-15T04:10:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmptyStringReturnZero -->
        <test-method signature="ReturnSumofThreeNumberWithCommaAndNewLineDelimiter()[pri:0, instance:TestCalculate@a1cdc6d]" started-at="2021-01-15T04:10:08 IST" name="ReturnSumofThreeNumberWithCommaAndNewLineDelimiter" finished-at="2021-01-15T04:10:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReturnSumofThreeNumberWithCommaAndNewLineDelimiter -->
        <test-method signature="ReturnSumofTwoNumberWithCommaDelimiter()[pri:0, instance:TestCalculate@a1cdc6d]" started-at="2021-01-15T04:10:08 IST" name="ReturnSumofTwoNumberWithCommaDelimiter" finished-at="2021-01-15T04:10:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReturnSumofTwoNumberWithCommaDelimiter -->
        <test-method signature="ReturnSumofTwoNumberWithNewLineDelimiter()[pri:0, instance:TestCalculate@a1cdc6d]" started-at="2021-01-15T04:10:08 IST" name="ReturnSumofTwoNumberWithNewLineDelimiter" finished-at="2021-01-15T04:10:08 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReturnSumofTwoNumberWithNewLineDelimiter -->
        <test-method signature="StringWithSingleNumber()[pri:0, instance:TestCalculate@a1cdc6d]" started-at="2021-01-15T04:10:08 IST" name="StringWithSingleNumber" finished-at="2021-01-15T04:10:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StringWithSingleNumber -->
        <test-method signature="StringWithnegativeNumberReturnsException()[pri:0, instance:TestCalculate@a1cdc6d]" started-at="2021-01-15T04:10:08 IST" name="StringWithnegativeNumberReturnsException" finished-at="2021-01-15T04:10:08 IST" duration-ms="2" status="PASS">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[String contains Negative Input-1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: String contains Negative Input-1
at Calculator.CheckforNegatives(Calculator.java:61)
at Calculator.CalculateSum(Calculator.java:39)
at Calculator.calculate(Calculator.java:25)
at TestCalculate.StringWithnegativeNumberReturnsException(TestCalculate.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StringWithnegativeNumberReturnsException -->
        <test-method signature="ValuesGreaterThan1000AreIgnored()[pri:0, instance:TestCalculate@a1cdc6d]" started-at="2021-01-15T04:10:08 IST" name="ValuesGreaterThan1000AreIgnored" finished-at="2021-01-15T04:10:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValuesGreaterThan1000AreIgnored -->
      </class> <!-- TestCalculate -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
