<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="nikunj-20h1cto1ww" failures="1" tests="7" name="TestCalculate" time="0.030" errors="0" timestamp="2021-01-15T03:08:17 IST" skipped="0">
  <testcase classname="TestCalculate" name="ReturnSumofThreeNumberWithCommaAndNewLineDelimiter" time="0.002"/>
  <system-out/>
  <testcase classname="TestCalculate" name="StringWithnegativeNumberReturnsException" time="0.002"/>
  <system-out/>
  <testcase classname="TestCalculate" name="ValuesGreaterThan1000AreIgnored" time="0.002">
    <failure message="expected [7] but found [1010]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [7] but found [1010]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at TestCalculate.ValuesGreaterThan1000AreIgnored(TestCalculate.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValuesGreaterThan1000AreIgnored -->
  <system-out/>
  <testcase classname="TestCalculate" name="StringWithSingleNumber" time="0.001"/>
  <system-out/>
  <testcase classname="TestCalculate" name="EmptyStringReturnZero" time="0.020"/>
  <system-out/>
  <testcase classname="TestCalculate" name="ReturnSumofTwoNumberWithNewLineDelimiter" time="0.001"/>
  <system-out/>
  <testcase classname="TestCalculate" name="ReturnSumofTwoNumberWithCommaDelimiter" time="0.002"/>
  <system-out/>
</testsuite> <!-- TestCalculate -->
